export enum TransactionMutationType {
	SET_BALANCE = 'SET_BALANCE',
	SET_INCOME = 'SET_INCOME',
	SET_EXPENSES = 'SET_EXPENSES',
	SET_TRANSACTIONS = 'SET_TRANSACTIONS',
	ADD_TRANSACTION = 'ADD_TRANSACTION',
	DELETE_TRANSACTION = 'DELETE_TRANSACTION',
}